name: Release

on:
  push:
    tags:
      - "20[0-9][0-9].[0-9][0-9].*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Validate CalVer tag
      run: |
        tag=${GITHUB_REF#refs/tags/}
        if ! [[ $tag =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]+$ ]]; then
          echo "Invalid tag format. Expected YYYY.MM.MINOR (e.g., 2025.08.1)"
          exit 1
        fi

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25

    - name: Build all platforms
      run: make build-all

    - name: Upload Linux binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/pce-linux-amd64
        asset_name: pce-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload Windows binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/pce-windows-amd64.exe
        asset_name: pce-windows-amd64.exe
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload macOS (Intel) binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/pce-darwin-amd64
        asset_name: pce-darwin-amd64
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload macOS (Apple Silicon) binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/pce-darwin-arm64
        asset_name: pce-darwin-arm64
        tag: ${{ github.ref }}
        overwrite: true