name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25

    - name: Run unit tests
      run: make test-unit

    # Run integration tests only on pull requests to main
    - name: Run integration tests
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      run: make test-integration
